name: alrefadah
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  very_good_analysis: ^7.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  icons_launcher: ^3.0.1
  flutter_bloc: ^9.1.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  hijri: ^3.0.0
  flutter_spinkit: ^5.2.1
  jwt_decoder: ^2.0.1
  connectivity_plus: ^5.0.2
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  fl_chart: ^0.71.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/images/endOfPage.png
    - assets/images/recaptcha.png
    - assets/icons/Frame 2.png
    - .env
    - assets/svg/bus_status/


  fonts:
    - family: GE SS Two
      fonts:
        - asset: assets/fonts/GE SS Two/GE SS Two_MEDIUM_5.otf
          weight: 500
        - asset: assets/fonts/GE SS Two/GE SS Two_TEXT_LIGHT.otf
          weight: 200
        - asset: assets/fonts/GE SS Two/GE SS Two_Bold_4.otf
          weight: 700
    - family: FF Shamel Family
      fonts:
        - asset: assets/fonts/FFShamelFamily.ttf
 
icons_launcher:
  image_path: "assets/icons/Frame 2.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
# dart run icons_launcher:create